In [1]:
import numpy as np
import scipy as sc
from math import sqrt

In [2]:
A = np.array([[0, 1, 1], [sqrt(2), 2, 0], [0, 1, 1]])

In [3]:
A

array([[0.        , 1.        , 1.        ],
       [1.41421356, 2.        , 0.        ],
       [0.        , 1.        , 1.        ]])

In [13]:
U, s, VT = sc.linalg.svd(A)


In [14]:
U

array([[-0.40824829,  0.57735027, -0.70710678],
       [-0.81649658, -0.57735027,  0.        ],
       [-0.40824829,  0.57735027,  0.70710678]])

In [16]:
s

array([2.82842712e+00, 1.41421356e+00, 1.01465364e-17])

In [17]:
VT

array([[-4.08248290e-01, -8.66025404e-01, -2.88675135e-01],
       [-5.77350269e-01,  1.11022302e-16,  8.16496581e-01],
       [ 7.07106781e-01, -5.00000000e-01,  5.00000000e-01]])

In [21]:
si = np.diag(s)

In [22]:
B = U.dot(Sigma.dot(VT))

In [23]:
B

array([[-1.87623447e-16,  1.00000000e+00,  1.00000000e+00],
       [ 1.41421356e+00,  2.00000000e+00, -8.79548322e-17],
       [-1.36730966e-16,  1.00000000e+00,  1.00000000e+00]])